In [3]:
import numpy as np
import pandas as pd

In [6]:
np.random.seed(2727)
result = np.random.choice(["rock", "paper", "scissors"], size=(5,2), p = [1/3, 1/3, 1/3])
result

array([['rock', 'scissors'],
       ['rock', 'rock'],
       ['scissors', 'paper'],
       ['scissors', 'rock'],
       ['paper', 'paper']], dtype='<U8')

In [7]:
result = pd.DataFrame(result)
result

0         1
0      rock  scissors
1      rock      rock
2  scissors     paper
3  scissors      rock
4     paper     paper

In [8]:
def game(x,y):
    if(x == 0 and y == 1) or (x == 1  and y == 2) or (x == 2  and y == 0) :
        return "{a} wins {b}".format(a = x, b = y)   
    elif x == y:
        return "tie"
    else:
        return "{b} wins {a}".format(a = x, b = y)

In [9]:
def win(text):
    x,y = text[0],text[1]
    if x == y:
        return "tie"
    elif (x,y) in [("scissors", "paper"), ("paper", "rock"), ("rock", "scissors")]:
        return "%s wins %s" % (x,y)
    else:
        return "%s wins %s" % (y,x)

In [10]:
result["result"] = result.apply(win, axis = 1)
result

0         1               result
0      rock  scissors   rock wins scissors
1      rock      rock                  tie
2  scissors     paper  scissors wins paper
3  scissors      rock   rock wins scissors
4     paper     paper                  tie

In [11]:
b = np.array(range(1,17)) 
b.reshape((2,2,2,2))

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [12]:
a = np.array([11,12,13,14,15,16,17,18]) 
a = a.reshape((2,4))
a, type(a)

(array([[11, 12, 13, 14],
        [15, 16, 17, 18]]), numpy.ndarray)

In [ ]:
a + a

In [ ]:
a * a

In [13]:
b = np.matrix([1,2,3,4])
b = b.reshape((2,2))
b, type(b)

(matrix([[1, 2],
         [3, 4]]), numpy.matrix)

In [ ]:
b + b

In [ ]:
b

In [ ]:
c = a.reshape((2,2,2))
c, c[0,1,0]

In [ ]:
result.values, type(result.values), result.shape

In [1]:
from sklearn.linear_model import LinearRegression as lr

In [4]:
lr1 = lr().fit(X=np.array([1,2,3,4]).reshape(-1,1), y=[5,6,7,8])

In [5]:
lr1.coef_, lr1.intercept_

(array([1.]), 3.999999999999999)